### ISSUE TITLE
Can't resolve com.android.location.provider.GeofenceProvider

### ISSUE THREAD

**Issue by cxvx** [MindTheGapps/vendor_gapps-old#3]
I'm getting frequent crashes like this on current gapps and Lineage 15.1-20180226 (bullhead):

```
02-27 09:34:51.576 23171 23171 I zygote  : The ClassLoaderContext is a special shared library.
02-27 09:34:51.610 23171 23171 I LoadedApk: No resource references to update in package FFFFFFFFFFFFFFFFFFFFFF
02-27 09:34:51.700 23171 23171 W linker  : "/system/priv-app/PrebuiltGmsCore/PrebuiltGmsCore.apk!/lib/armeabi-v7a/libconscrypt_gmscore_jni.so" unused DT entry: type 0xf arg 0x1dc
02-27 09:34:51.701 23171 23171 V NativeCrypto: Registering com/google/android/gms/org/conscrypt/NativeCrypto's 276 native methods...
02-27 09:34:51.731 23171 23171 D NetworkSecurityConfig: No Network Security Config specified, using platform default
02-27 09:34:51.736 23171 23171 I ProviderInstaller: Installed default security provider GmsCore_OpenSSL
02-27 09:34:51.821 23171 23171 I DynamiteModule: Considering local module com.google.android.gms.googlecertificates:4 and remote module com.google.android.gms.googlecertificates:4
02-27 09:34:51.822 23171 23171 I DynamiteModule: Selected local version of com.google.android.gms.googlecertificates
02-27 09:34:52.108 23171 23171 I zygote  : Rejecting re-init on previously-failed class java.lang.Class<aqmb>: java.lang.NoClassDefFoundError: Failed resolution of: Lcom/android/location/provider/GeofenceProvider;
02-27 09:34:52.108 23171 23171 I zygote  :   at void com.google.android.location.geofencer.service.GeofenceProviderChimeraService.onCreate() (:com.google.android.gms@11976930:3)
02-27 09:34:52.108 23171 23171 I zygote  :   at void csh.onCreate() (:com.google.android.gms@11976930:1)
02-27 09:34:52.108 23171 23171 I zygote  :   at void leb.onCreate() (:com.google.android.gms@11976930:3)
02-27 09:34:52.108 23171 23171 I zygote  :   at void android.app.ActivityThread.handleCreateService(android.app.ActivityThread$CreateServiceData) (ActivityThread.java:3339)
02-27 09:34:52.108 23171 23171 I zygote  :   at void android.app.ActivityThread.-wrap4(android.app.ActivityThread, android.app.ActivityThread$CreateServiceData) (ActivityThread.java:-1)
02-27 09:34:52.108 23171 23171 I zygote  :   at void android.app.ActivityThread$H.handleMessage(android.os.Message) (ActivityThread.java:1677)
02-27 09:34:52.108 23171 23171 I zygote  :   at void android.os.Handler.dispatchMessage(android.os.Message) (Handler.java:106)
02-27 09:34:52.108 23171 23171 I zygote  :   at void android.os.Looper.loop() (Looper.java:164)
02-27 09:34:52.108 23171 23171 I zygote  :   at void android.app.ActivityThread.main(java.lang.String[]) (ActivityThread.java:6494)
02-27 09:34:52.108 23171 23171 I zygote  :   at java.lang.Object java.lang.reflect.Method.invoke(java.lang.Object, java.lang.Object[]) (Method.java:-2)
02-27 09:34:52.108 23171 23171 I zygote  :   at void com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run() (RuntimeInit.java:440)
02-27 09:34:52.108 23171 23171 I zygote  :   at void com.android.internal.os.ZygoteInit.main(java.lang.String[]) (ZygoteInit.java:807)
02-27 09:34:52.108 23171 23171 I zygote  : Caused by: java.lang.ClassNotFoundException: Didn't find class "com.android.location.provider.GeofenceProvider" on path: DexPathList[[zip file "/system/framework/com.android.media.remotedisplay.jar", zip file "/system/framework/com.android.location.provider.jar", zip file "/system/priv-app/PrebuiltGmsCore/PrebuiltGmsCore.apk"],nativeLibraryDirectories=[/system/priv-app/PrebuiltGmsCore/lib/arm, /system/fake-libs, /system/priv-app/PrebuiltGmsCore/PrebuiltGmsCore.apk!/lib/armeabi-v7a, /system/lib, /vendor/lib, /system/lib, /vendor/lib]]
02-27 09:34:52.108 23171 23171 I zygote  :   at java.lang.Class dalvik.system.BaseDexClassLoader.findClass(java.lang.String) (BaseDexClassLoader.java:125)
02-27 09:34:52.108 23171 23171 I zygote  :   at java.lang.Class java.lang.ClassLoader.loadClass(java.lang.String, boolean) (ClassLoader.java:379)
02-27 09:34:52.108 23171 23171 I zygote  :   at java.lang.Class java.lang.ClassLoader.loadClass(java.lang.String) (ClassLoader.java:312)
02-27 09:34:52.108 23171 23171 I zygote  :   at void com.google.android.location.geofencer.service.GeofenceProviderChimeraService.onCreate() (:com.google.android.gms@11976930:3)
02-27 09:34:52.108 23171 23171 I zygote  :   at void csh.onCreate() (:com.google.android.gms@11976930:1)
02-27 09:34:52.108 23171 23171 I zygote  :   at void leb.onCreate() (:com.google.android.gms@11976930:3)
02-27 09:34:52.108 23171 23171 I zygote  :   at void android.app.ActivityThread.handleCreateService(android.app.ActivityThread$CreateServiceData) (ActivityThread.java:3339)
02-27 09:34:52.108 23171 23171 I zygote  :   at void android.app.ActivityThread.-wrap4(android.app.ActivityThread, android.app.ActivityThread$CreateServiceData) (ActivityThread.java:-1)
02-27 09:34:52.108 23171 23171 I zygote  :   at void android.app.ActivityThread$H.handleMessage(android.os.Message) (ActivityThread.java:1677)
02-27 09:34:52.109 23171 23171 I zygote  :   at void android.os.Handler.dispatchMessage(android.os.Message) (Handler.java:106)
02-27 09:34:52.109 23171 23171 I zygote  :   at void android.os.Looper.loop() (Looper.java:164)
02-27 09:34:52.109 23171 23171 I zygote  :   at void android.app.ActivityThread.main(java.lang.String[]) (ActivityThread.java:6494)
02-27 09:34:52.109 23171 23171 I zygote  :   at java.lang.Object java.lang.reflect.Method.invoke(java.lang.Object, java.lang.Object[]) (Method.java:-2)
02-27 09:34:52.109 23171 23171 I zygote  :   at void com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run() (RuntimeInit.java:440)
02-27 09:34:52.109 23171 23171 I zygote  :   at void com.android.internal.os.ZygoteInit.main(java.lang.String[]) (ZygoteInit.java:807)
02-27 09:34:52.109 23171 23171 I zygote  : 
02-27 09:34:52.111 23171 23171 D AndroidRuntime: Shutting down VM
02-27 09:34:52.112 23171 23171 E AndroidRuntime: FATAL EXCEPTION: main
02-27 09:34:52.112 23171 23171 E AndroidRuntime: Process: com.google.android.gms.persistent, PID: 23171
02-27 09:34:52.112 23171 23171 E AndroidRuntime: java.lang.NoClassDefFoundError: Failed resolution of: Laqmb;
02-27 09:34:52.112 23171 23171 E AndroidRuntime:        at com.google.android.location.geofencer.service.GeofenceProviderChimeraService.onCreate(:com.google.android.gms@11976930:3)
02-27 09:34:52.112 23171 23171 E AndroidRuntime:        at csh.onCreate(:com.google.android.gms@11976930:1)
02-27 09:34:52.112 23171 23171 E AndroidRuntime:        at leb.onCreate(:com.google.android.gms@11976930:3)
02-27 09:34:52.112 23171 23171 E AndroidRuntime:        at android.app.ActivityThread.handleCreateService(ActivityThread.java:3339)
02-27 09:34:52.112 23171 23171 E AndroidRuntime:        at android.app.ActivityThread.-wrap4(Unknown Source:0)
02-27 09:34:52.112 23171 23171 E AndroidRuntime:        at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1677)
02-27 09:34:52.112 23171 23171 E AndroidRuntime:        at android.os.Handler.dispatchMessage(Handler.java:106)
02-27 09:34:52.112 23171 23171 E AndroidRuntime:        at android.os.Looper.loop(Looper.java:164)
02-27 09:34:52.112 23171 23171 E AndroidRuntime:        at android.app.ActivityThread.main(ActivityThread.java:6494)
02-27 09:34:52.112 23171 23171 E AndroidRuntime:        at java.lang.reflect.Method.invoke(Native Method)
02-27 09:34:52.112 23171 23171 E AndroidRuntime:        at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:440)
02-27 09:34:52.112 23171 23171 E AndroidRuntime:        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:807)
02-27 09:34:52.112 23171 23171 E AndroidRuntime: Caused by: java.lang.ClassNotFoundException: aqmb
02-27 09:34:52.112 23171 23171 E AndroidRuntime:        at java.lang.VMClassLoader.findLoadedClass(Native Method)
02-27 09:34:52.112 23171 23171 E AndroidRuntime:        at java.lang.ClassLoader.findLoadedClass(ClassLoader.java:738)
02-27 09:34:52.112 23171 23171 E AndroidRuntime:        at java.lang.ClassLoader.loadClass(ClassLoader.java:363)
02-27 09:34:52.112 23171 23171 E AndroidRuntime:        at java.lang.ClassLoader.loadClass(ClassLoader.java:312)
02-27 09:34:52.112 23171 23171 E AndroidRuntime:        ... 12 more
02-27 09:34:52.112 23171 23171 E AndroidRuntime: Caused by: java.lang.NoClassDefFoundError: Failed resolution of: Lcom/android/location/provider/GeofenceProvider;
02-27 09:34:52.112 23171 23171 E AndroidRuntime:        ... 12 more
02-27 09:34:52.112 23171 23171 E AndroidRuntime: Caused by: java.lang.ClassNotFoundException: Didn't find class "com.android.location.provider.GeofenceProvider" on path: DexPathList[[zip file "/system/framework/com.android.media.remotedisplay.jar", zip file "/system/framework/com.android.location.provider.jar", zip file "/system/priv-app/PrebuiltGmsCore/PrebuiltGmsCore.apk"],nativeLibraryDirectories=[/system/priv-app/PrebuiltGmsCore/lib/arm, /system/fake-libs, /system/priv-app/PrebuiltGmsCore/PrebuiltGmsCore.apk!/lib/armeabi-v7a, /system/lib, /vendor/lib, /system/lib, /vendor/lib]]
02-27 09:34:52.112 23171 23171 E AndroidRuntime:        at dalvik.system.BaseDexClassLoader.findClass(BaseDexClassLoader.java:125)
02-27 09:34:52.112 23171 23171 E AndroidRuntime:        at java.lang.ClassLoader.loadClass(ClassLoader.java:379)
02-27 09:34:52.112 23171 23171 E AndroidRuntime:        at java.lang.ClassLoader.loadClass(ClassLoader.java:312)
02-27 09:34:52.112 23171 23171 E AndroidRuntime:        ... 12 more
02-27 09:34:52.112 23171 23171 E AndroidRuntime:        Suppressed: java.io.IOException: No original dex files found for dex location /system/framework/com.android.location.provider.jar
02-27 09:34:52.112 23171 23171 E AndroidRuntime:                at dalvik.system.DexFile.openDexFileNative(Native Method)
02-27 09:34:52.112 23171 23171 E AndroidRuntime:                at dalvik.system.DexFile.openDexFile(DexFile.java:353)
02-27 09:34:52.112 23171 23171 E AndroidRuntime:                at dalvik.system.DexFile.<init>(DexFile.java:100)
02-27 09:34:52.112 23171 23171 E AndroidRuntime:                at dalvik.system.DexFile.<init>(DexFile.java:74)
02-27 09:34:52.112 23171 23171 E AndroidRuntime:                at dalvik.system.DexPathList.loadDexFile(DexPathList.java:374)
02-27 09:34:52.112 23171 23171 E AndroidRuntime:                at dalvik.system.DexPathList.makeDexElements(DexPathList.java:337)
02-27 09:34:52.112 23171 23171 E AndroidRuntime:                at dalvik.system.DexPathList.<init>(DexPathList.java:157)
02-27 09:34:52.112 23171 23171 E AndroidRuntime:                at dalvik.system.BaseDexClassLoader.<init>(BaseDexClassLoader.java:65)
02-27 09:34:52.112 23171 23171 E AndroidRuntime:                at dalvik.system.PathClassLoader.<init>(PathClassLoader.java:64)
02-27 09:34:52.112 23171 23171 E AndroidRuntime:                at com.android.internal.os.ClassLoaderFactory.createClassLoader(ClassLoaderFactory.java:73)
02-27 09:34:52.112 23171 23171 E AndroidRuntime:                at com.android.internal.os.ClassLoaderFactory.createClassLoader(ClassLoaderFactory.java:88)
02-27 09:34:52.112 23171 23171 E AndroidRuntime:                at android.app.ApplicationLoaders.getClassLoader(ApplicationLoaders.java:69)
02-27 09:34:52.112 23171 23171 E AndroidRuntime:                at android.app.ApplicationLoaders.getClassLoader(ApplicationLoaders.java:35)
02-27 09:34:52.112 23171 23171 E AndroidRuntime:                at android.app.LoadedApk.createOrUpdateClassLoaderLocked(LoadedApk.java:693)
02-27 09:34:52.112 23171 23171 E AndroidRuntime:                at android.app.LoadedApk.getClassLoader(LoadedApk.java:727)
02-27 09:34:52.112 23171 23171 E AndroidRuntime:                at android.app.LoadedApk.getResources(LoadedApk.java:954)
02-27 09:34:52.112 23171 23171 E AndroidRuntime:                at android.app.ContextImpl.createAppContext(ContextImpl.java:2270)
02-27 09:34:52.112 23171 23171 E AndroidRuntime:                at android.app.ActivityThread.handleBindApplication(ActivityThread.java:5639)
02-27 09:34:52.112 23171 23171 E AndroidRuntime:                at android.app.ActivityThread.-wrap1(Unknown Source:0)
02-27 09:34:52.112 23171 23171 E AndroidRuntime:                at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1656)
02-27 09:34:52.112 23171 23171 E AndroidRuntime:                ... 6 more
02-27 09:34:52.126 23171 23171 I GCore-Chimera-Crash: Cg8KCWNvbnRhaW5lchCpjEk=
02-27 09:34:52.126 23171 23171 I GCore-Chimera-Crash: GCore-Chimera-Crash
02-27 09:34:52.136 23171 23171 I DeviceDrDatabaseHelper: Cleaning stale data from database!
02-27 09:34:52.164 23171 23171 W DeviceDoctorHandler: Crash Hash: a4fa291bec5aef6cb02e0a1ecfa12510ee4f8962
02-27 09:34:52.190 23171 23171 W DeviceDoctorHandler: Shushing crash due to popup frequency.
02-27 09:34:52.192 23171 23171 E DeviceDoctorHandler: FATAL EXCEPTION: main
02-27 09:34:52.192 23171 23171 E DeviceDoctorHandler: Process: com.google.android.gms.persistent, PID: 23171
02-27 09:34:52.192 23171 23171 E DeviceDoctorHandler: java.lang.NoClassDefFoundError: Failed resolution of: Laqmb;
02-27 09:34:52.192 23171 23171 E DeviceDoctorHandler:   at com.google.android.location.geofencer.service.GeofenceProviderChimeraService.onCreate(:com.google.android.gms@11976930:3)
02-27 09:34:52.192 23171 23171 E DeviceDoctorHandler:   at csh.onCreate(:com.google.android.gms@11976930:1)
02-27 09:34:52.192 23171 23171 E DeviceDoctorHandler:   at leb.onCreate(:com.google.android.gms@11976930:3)
02-27 09:34:52.192 23171 23171 E DeviceDoctorHandler:   at android.app.ActivityThread.handleCreateService(ActivityThread.java:3339)
02-27 09:34:52.192 23171 23171 E DeviceDoctorHandler:   at android.app.ActivityThread.-wrap4(Unknown Source:0)
02-27 09:34:52.192 23171 23171 E DeviceDoctorHandler:   at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1677)
02-27 09:34:52.192 23171 23171 E DeviceDoctorHandler:   at android.os.Handler.dispatchMessage(Handler.java:106)
02-27 09:34:52.192 23171 23171 E DeviceDoctorHandler:   at android.os.Looper.loop(Looper.java:164)
02-27 09:34:52.192 23171 23171 E DeviceDoctorHandler:   at android.app.ActivityThread.main(ActivityThread.java:6494)
02-27 09:34:52.192 23171 23171 E DeviceDoctorHandler:   at java.lang.reflect.Method.invoke(Native Method)
02-27 09:34:52.192 23171 23171 E DeviceDoctorHandler:   at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:440)
02-27 09:34:52.192 23171 23171 E DeviceDoctorHandler:   at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:807)
02-27 09:34:52.192 23171 23171 E DeviceDoctorHandler: Caused by: java.lang.ClassNotFoundException: aqmb
02-27 09:34:52.192 23171 23171 E DeviceDoctorHandler:   at java.lang.VMClassLoader.findLoadedClass(Native Method)
02-27 09:34:52.192 23171 23171 E DeviceDoctorHandler:   at java.lang.ClassLoader.findLoadedClass(ClassLoader.java:738)
02-27 09:34:52.192 23171 23171 E DeviceDoctorHandler:   at java.lang.ClassLoader.loadClass(ClassLoader.java:363)
02-27 09:34:52.192 23171 23171 E DeviceDoctorHandler:   at java.lang.ClassLoader.loadClass(ClassLoader.java:312)
02-27 09:34:52.192 23171 23171 E DeviceDoctorHandler:   ... 12 more
02-27 09:34:52.192 23171 23171 E DeviceDoctorHandler: Caused by: java.lang.NoClassDefFoundError: Failed resolution of: Lcom/android/location/provider/GeofenceProvider;
02-27 09:34:52.192 23171 23171 E DeviceDoctorHandler:   ... 12 more
02-27 09:34:52.192 23171 23171 E DeviceDoctorHandler: Caused by: java.lang.ClassNotFoundException: Didn't find class "com.android.location.provider.GeofenceProvider" on path: DexPathList[[zip file "/system/framework/com.android.media.remotedisplay.jar", zip file "/system/framework/com.android.location.provider.jar", zip file "/system/priv-app/PrebuiltGmsCore/PrebuiltGmsCore.apk"],nativeLibraryDirectories=[/system/priv-app/PrebuiltGmsCore/lib/arm, /system/fake-libs, /system/priv-app/PrebuiltGmsCore/PrebuiltGmsCore.apk!/lib/armeabi-v7a, /system/lib, /vendor/lib, /system/lib, /vendor/lib]]
02-27 09:34:52.192 23171 23171 E DeviceDoctorHandler:   at dalvik.system.BaseDexClassLoader.findClass(BaseDexClassLoader.java:125)
02-27 09:34:52.192 23171 23171 E DeviceDoctorHandler:   at java.lang.ClassLoader.loadClass(ClassLoader.java:379)
02-27 09:34:52.192 23171 23171 E DeviceDoctorHandler:   at java.lang.ClassLoader.loadClass(ClassLoader.java:312)
02-27 09:34:52.192 23171 23171 E DeviceDoctorHandler:   ... 12 more
02-27 09:34:52.192 23171 23171 E DeviceDoctorHandler:   Suppressed: java.io.IOException: No original dex files found for dex location /system/framework/com.android.location.provider.jar
02-27 09:34:52.192 23171 23171 E DeviceDoctorHandler:           at dalvik.system.DexFile.openDexFileNative(Native Method)
02-27 09:34:52.192 23171 23171 E DeviceDoctorHandler:           at dalvik.system.DexFile.openDexFile(DexFile.java:353)
02-27 09:34:52.192 23171 23171 E DeviceDoctorHandler:           at dalvik.system.DexFile.<init>(DexFile.java:100)
02-27 09:34:52.192 23171 23171 E DeviceDoctorHandler:           at dalvik.system.DexFile.<init>(DexFile.java:74)
02-27 09:34:52.192 23171 23171 E DeviceDoctorHandler:           at dalvik.system.DexPathList.loadDexFile(DexPathList.java:374)
02-27 09:34:52.192 23171 23171 E DeviceDoctorHandler:           at dalvik.system.DexPathList.makeDexElements(DexPathList.java:337)
02-27 09:34:52.192 23171 23171 E DeviceDoctorHandler:           at dalvik.system.DexPathList.<init>(DexPathList.java:157)
02-27 09:34:52.192 23171 23171 E DeviceDoctorHandler:           at dalvik.system.BaseDexClassLoader.<init>(BaseDexClassLoader.java:65)
02-27 09:34:52.192 23171 23171 E DeviceDoctorHandler:           at dalvik.system.PathClassLoader.<init>(PathClassLoader.java:64)
02-27 09:34:52.192 23171 23171 E DeviceDoctorHandler:           at com.android.internal.os.ClassLoaderFactory.createClassLoader(ClassLoaderFactory.java:73)
02-27 09:34:52.192 23171 23171 E DeviceDoctorHandler:           at com.android.internal.os.ClassLoaderFactory.createClassLoader(ClassLoaderFactory.java:88)
02-27 09:34:52.192 23171 23171 E DeviceDoctorHandler:           at android.app.ApplicationLoaders.getClassLoader(ApplicationLoaders.java:69)
02-27 09:34:52.192 23171 23171 E DeviceDoctorHandler:           at android.app.ApplicationLoaders.getClassLoader(ApplicationLoaders.java:35)
02-27 09:34:52.192 23171 23171 E DeviceDoctorHandler:           at android.app.LoadedApk.createOrUpdateClassLoaderLocked(LoadedApk.java:693)
02-27 09:34:52.192 23171 23171 E DeviceDoctorHandler:           at android.app.LoadedApk.getClassLoader(LoadedApk.java:727)
02-27 09:34:52.192 23171 23171 E DeviceDoctorHandler:           at android.app.LoadedApk.getResources(LoadedApk.java:954)
02-27 09:34:52.192 23171 23171 E DeviceDoctorHandler:           at android.app.ContextImpl.createAppContext(ContextImpl.java:2270)
02-27 09:34:52.192 23171 23171 E DeviceDoctorHandler:           at android.app.ActivityThread.handleBindApplication(ActivityThread.java:5639)
02-27 09:34:52.192 23171 23171 E DeviceDoctorHandler:           at android.app.ActivityThread.-wrap1(Unknown Source:0)
02-27 09:34:52.192 23171 23171 E DeviceDoctorHandler:           at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1656)
02-27 09:34:52.192 23171 23171 E DeviceDoctorHandler:           ... 6 more
02-27 09:34:52.192 23171 23171 E DeviceDoctorHandler: 
02-27 09:34:52.212 23171 23171 I Process : Sending signal. PID: 23171 SIG: 9
```

**Comment by javelinanddart** [comment]
Can you replicate this on a clean flash? I'm not seeing any crashes whatsoever on my device

**Comment by cxvx** [comment]
Yes, on a clean /system + /vendor, but non-clean /data.

I was able to dig a bit deeper, although unfortunately I'm not very familiar with Android or Dalvik.

bullhead/Nexus 5x is an arm64 device. I guess this is confirmed by

```
bullhead:/ # grep ^ro.product.cpu.abi /system/build.prop
ro.product.cpu.abi=arm64-v8a
ro.product.cpu.abilist=arm64-v8a,armeabi-v7a,armeabi
ro.product.cpu.abilist32=armeabi-v7a,armeabi
ro.product.cpu.abilist64=arm64-v8a
```

I saw an error message complaining about a missing `libleveldbjni.so` (sorry lost the actual full error) and a search path like this:
`nativeLibraryDirectories=[/system/priv-app/PrebuiltGmsCore/lib/arm, /system/fake-libs, /system/priv-app/PrebuiltGmsCore/PrebuiltGmsCore.apk!/lib/armeabi-v7a, /system/lib, /vendor/lib, /system/lib, /vendor/lib]`

PrebuiltGmsCore.apk does have that file, but in `/lib/arm64-v8a`, as it's the 64 bit build. No idea why apparently the 32 bit launcher is running the binary.

I installed the 32 bit build, and this error disappeared, but now I'm basically back to the initial error:

```
02-27 23:26:51.044  4158  4158 E AndroidRuntime: Caused by: java.lang.ClassNotFoundException: Didn't find class "com.android.location.provider.FusedProvider" on path: DexPathList[[zip file "/system/framework/com.android.media.remotedisplay.jar", zip file "/system/framework/com.android.location.provider.jar", zip file "/system/priv-app/PrebuiltGmsCore/PrebuiltGmsCore.apk"],nativeLibraryDirectories=[/system/priv-app/PrebuiltGmsCore/lib/arm, /system/fake-libs, /system/priv-app/PrebuiltGmsCore/PrebuiltGmsCore.apk!/lib/armeabi-v7a, /system/lib, /vendor/lib, /system/lib, /vendor/lib]]
02-27 23:26:51.044  4158  4158 E AndroidRuntime:        at dalvik.system.BaseDexClassLoader.findClass(BaseDexClassLoader.java:125)
02-27 23:26:51.044  4158  4158 E AndroidRuntime:        at java.lang.ClassLoader.loadClass(ClassLoader.java:379)
02-27 23:26:51.044  4158  4158 E AndroidRuntime:        at java.lang.ClassLoader.loadClass(ClassLoader.java:312)
02-27 23:26:51.044  4158  4158 E AndroidRuntime:        ... 18 more
02-27 23:26:51.044  4158  4158 E AndroidRuntime:        Suppressed: java.io.IOException: No original dex files found for dex location /system/framework/com.android.location.provider.jar
```

The `com.android.location.provider.jar` on the device is tiny and only contains an empty `META-INF/MANIFEST.MF`.

**Comment by javelinanddart** [comment]
If you wouldn't mind testing on a clean /data (actual format data in twrp, not the "advanced wipe" that doesn't actually format the partition), I would appreciate it. Several people have tested arm64 and none have reported issues at all. Not sure why your bullhead is being weird :/

**Comment by javelinanddart** [comment]
Closing as stale.
